### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by nstephenh** [nstephenh/panoptica-heresy#1]
**Panoptica 1.0** 

Core book
- [x] Destroyer
- [ ] Pistol (Cannot assault?)? Pistol doesn't exist in base files
- [x] Non-Vehicle Unit Types
- [ ] Vehicle Unit Types, doesn't appear to exist in base files
- [x] Fortified Wall, Imperial Bunker (didn't add the size guidance on purpose)
- [x] Special Rules

Liber Astartes and Hereticus
- [ ] Weapons and Equipment Upgrades (By far the largest chunk, should wait till base files have it done as well
- [x] Deadnoughts: We didn't include the "two melee weapons" bit to begin with
- [ ] Breacher Dedicated Transports
- [ ] Outrider Squad Wounds
- [ ] Dreadclaw assault vehicle/orbital assault vehicle
- [ ] Leviathan, two weapons reminder text
- [ ] Thunderhawk, give twin-linked to heavy bolters
- [ ] Armored Spearhead limitation
- [ ] Brethren of Iron grant legiones astartes to automata
- [ ] Fury of the Ancients, extra VP
- [ ] Apothecaries can join shamshir jetbike squad (was not in regular special rules)
- [x] Special Rules
- [x] Weapons
- [ ] Bikes
- [x] Non-bike wargear
- [ ] Teleport Strike for Sons of Horus and Night Lords

Liber Astartes

Liber Hereticus

Legacies of the Age of Darkness

Exemplary Battles

Zone Mortalis

Ka'Bandha

Liber Mechanicum
- [ ] Unit Changes
- [ ] Special Rule Changes
- [ ] Weapons Changes
- [ ] Additional Weargear options

 Additional Special Rules Section
- [ ] All of them

Additional Game Modes
- [ ] Praetorian
- [ ] Centurion
- [ ] Decurion

**Liber Centura**
Units 
- [ ] So many
Appendencies
- [ ] Additional Rites of War
- [ ] Modifications to unaligned rites of war
- [ ] Additonal Consuls
- [ ] Dreadnought Consuls
- [ ] Special Rules
- [ ] Weapons
- [ ] Even more weapons
- [ ] Wargear
